### ISSUE TITLE
https postでエラーが返ってくるようになった

### ISSUE THREAD

**Issue by yochy4671** [nara256/IIJMachinistClient#3]
6/28 18:00ころからhttps postがエラーになって返ってくるようになりました．
ちょうどMachinistのメンテナンスが終了し運用を再開した時期と思われるのですが，
何かご存知ありませんか．

```
10:11:16.632 -> [HTTPS] begin...  URI=https://gw.machinist.iij.jp:443/endpoint
10:11:16.632 -> POST {(中略)}
10:11:16.679 -> status=-1
10:16:17.692 -> [HTTPS] begin...  URI=https://gw.machinist.iij.jp:443/endpoint
10:16:17.692 -> POST {(中略)}
10:16:17.740 -> status=-1
```

Raspberry Piからcurlを使ってpostする分には問題なく動作しています．

**Comment by nara256** [comment]
すみません、反応が遅くなりました。
手元のESP32で動作確認してみたところ、正しく200が返ってくるようでした。
今回のMachinistのメンテナンスでサーバのIPアドレスが変わったようなので、メンテナンス直後だとDNSが古いサーバを見ていたのかもしれません。
現時点では正しく動くと思いますので、確認いただけますでしょうか。

**Comment by yochy4671** [comment]
使用しているのはESP8266でして，
fingerprintが古くなったからエラーになっていて，
値を更新することでpostできるようになった，
というところまで確認できています．

この週末にpull request出そうと思ってました．
fingerprintの値を更新してもらえるでしょうか．

**Comment by nara256** [comment]
なるほど。失礼しました。
Pull request お待ちしております。
